// Aggregated compilation unit for Arduino sketches.
// Arduino only compiles sources in the sketch root, so include nested sources here.

#include "command/SLinkCommandSenderStateSync.cpp"
#include "command/SLinkUnitCommandSender.cpp"
#include "debug/SLinkDebugPrinter.cpp"
#include "frame/SLinkFrameAssembler.cpp"
#include "frame/SLinkFrameBuilder.cpp"
#include "frame/SLinkFrameCallbacks.cpp"
#include "intent/SLinkIntentArbiter.cpp"
#include "intent/SLinkIntentProcessor.cpp"
#include "intent/SLinkIntentQueue.cpp"
#include "intent/SLinkIntentQueueAdapter.cpp"
#include "io/SLinkCommandConsole.cpp"
#include "io/SLinkPrettyPrinter.cpp"
#include "system/SLinkSystem.cpp"
#include "transport/SLinkBusState.cpp"
#include "transport/SLinkDecode.cpp"
#include "transport/SLinkEdgeCapture.cpp"
#include "transport/SLinkRx.cpp"
#include "transport/SLinkSymbolDecoder.cpp"
#include "transport/SLinkTx.cpp"
#include "transport/SLinkTxGate.cpp"
#include "unit/SLinkUnitEventBus.cpp"
#include "unit/SLinkUnitEventHandler.cpp"
#include "unit/SLinkUnitEventPublisher.cpp"
#include "unit/SLinkUnitStateStore.cpp"
#include "ui/UiApp.cpp"
#include "ui/UiAdapter.cpp"
